### ISSUE TITLE
awesome

### ISSUE THREAD

**Issue by vc1** [marirs/sigma-convert#1]
![7f06e3e454b725a6abd305e948a18aca](https://github.com/marirs/sigma-convert/assets/9018903/8fd06fc8-6a23-4927-a1e5-94ba9ad5af4f)

**Comment by vc1** [comment]
Which license does this project use?

**Comment by marirs** [comment]
Oh Sorry - will add the LICENCE. Thx for the reminder :)
It will be MIT

**Comment by marirs** [comment]
updated to MIT :)
