### ISSUE TITLE
The server resource path seems to be hard-coded

### ISSUE THREAD

**Issue by vc1** [marirs/sigma-convert#2]
https://github.com/marirs/sigma-convert/tree/master/dist

<img width="365" alt="image" src="https://github.com/marirs/sigma-convert/assets/9018903/03e65de7-4a62-44b1-b90e-90f04645537f">

```bash
❯ ./sigmac_api_server_macos_x86-64 --config ./configs/config.sample.yml
Error: FileServer path '/Users/sriramg/Documents/Dev/Rust/sigma-convert/sigmac-api-server/dist' is not a directory.
   >> Aborting early to prevent inevitable handler failure.
thread 'main' panicked at 'invalid directory: refusing to continue', /Users/sriramg/Documents/Dev/Rust/sigma-convert/sigmac-api-server/src/server/mod.rs:163:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/marirs/sigma-convert/blob/1031c9ddca81c0cec655ce04c4c5c7690039a895/sigmac-api-server/src/server/mod.rs#L163

https://api.rocket.rs/master/rocket/fs/macro.relative.html

https://github.com/SergioBenitez/Rocket/blob/f41474dd6136db0fe744907e06f8b38136259066/core/lib/src/fs/server.rs#L444-L452

<img width="1321" alt="image" src="https://github.com/marirs/sigma-convert/assets/9018903/35972dd8-b2be-4410-8232-6e904241f45d">

------

It can run successfully after recompiling on my computer

<img width="581" alt="image" src="https://github.com/marirs/sigma-convert/assets/9018903/765b8ee4-60d5-443c-97b4-f95215fccabe">

<img width="1356" alt="image" src="https://github.com/marirs/sigma-convert/assets/9018903/a40c6911-bd01-4485-b503-d95738c3d391">

**Comment by marirs** [comment]
Thats funny.. Lemme check on that and see where I might have hard coded it.. I typically dont hard code these stuffs.. lemme check on it!
Thanks for pointing that out

**Comment by marirs** [comment]
Ok the relative! macro is similar to the include_str! macro. at compile time it takes the current path and puts it into the binary.. let me try something else .

Again thanks so much for letting me know

**Comment by marirs** [comment]
Now you can add the path in the config.yml where the static can be served from.

Thanks again :)
